import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Providers";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import Link from "next/link";
import Logout from "@/components/Logout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession(authOptions);
    console.log("SERVER SESSION: ", session);
    return (
        <html lang="en">
            <body className={inter.className}>
                <nav>
                    {!!session && <Logout />}
                    {!session && <Link href={"/login"}>Log In</Link>}
                </nav>
                <AuthProvider>{children}</AuthProvider>
            </body>
        </html>
    );
}
