import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Providers";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import Navbar from "@/components/Navbar/Navbar";
import Notifications from "@/components/Notifications";
import { auth } from "@/helpers/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();
    console.log("SERVER SESSION: ", session);
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthProvider>
                    <Notifications>
                        <Navbar></Navbar>
                        {children}
                    </Notifications>
                </AuthProvider>
            </body>
        </html>
    );
}

// export const revalidate = 0;
